import Button from '@/components/Button';
import Github from '@/components/icons/Github';
import Head from 'next/head';
import { loginWithGithub, onAuthStateChanged } from '../firebase/client';
import { useState, useEffect } from 'react';
import Avatar from '@/components/Avatar';
import Logo from '@/components/Logo';

type User =
	| {
			avatar: string;
			name: string;
			email: string;
	  }
	| undefined;

export default function Home() {
	const [user, setUser] = useState<User>(undefined);

	useEffect(() => {
		onAuthStateChanged(setUser);
	}, []);

	const handleLogin = () => {
		loginWithGithub();
	};

	return (
		<>
			<Head>
				<title>Twitter clone</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className='grid h-screen max-w-2xl m-auto place-items-center place-content-center'>
				<Logo className='h-40 m-auto' />
				<h1 className='text-4xl font-bold text-orange-400'>Fake twitter</h1>
				<h2 className='text-xl font-semibold text-orange-50'>
					Believe me, this is not Twitter 🙂
				</h2>
				{user === null && (
					<Button className='flex gap-1 align-center ' onClick={handleLogin}>
						<Github className='w-7 text-orange-50'></Github>Login with Github
					</Button>
				)}
				{user && (
					<div className='flex items-center w-full space-x-4'>
						<div className='flex-shrink-0'>
							<Avatar img={user.avatar} />
						</div>
						<div className='flex-1 min-w-0'>
							<p className='text-base font-medium text-gray-900 truncate dark:text-white'>
								{user.name}
							</p>
							<p className='text-sm text-gray-500 truncate dark:text-gray-400'>
								{user.email}
							</p>
						</div>
					</div>
				)}
			</main>
		</>
	);
}
